name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 */24 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: chittivalasa124
          outputs: |
            dist/github-contribution-grid-snake.gif?color_snake=#00FFFF

      - name: Publish snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
